services:
  redis:
    image: redis:8.6.1-alpine
    volumes:
      - ./redis:/data
    networks:
      - back_net
    ports:
      - 6379:6379
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'redis-cli ping | grep PONG'"]
      start_period: 30s
      start_interval: 5s
      interval: 60s
      retries: 5
    restart: unless-stopped
  
  qdrant:
    image: qdrant/qdrant:v1.16
    restart: unless-stopped
    networks:
      - back_net
      - airflow_net
    volumes:
      - ./qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
      
  vllm_llm:
    image: 'ghcr.io/ggml-org/llama.cpp:server-cuda12-b8840'
    runtime: nvidia
    ipc: host
    volumes:
      - ./llama-models:/models
    command: >
      -m ${LLAMA_LLM_MODEL}
      --jinja
      -fa 1 -cmoe
      -c 65536
      --temp 1.0
      --min-p 0.0 --top-p 0.95 --top-k 20
      --presence_penalty 1.5
      --repeat-penalty 1.0
      --chat-template-kwargs "{\"enable_thinking\": false}"
      --host 0.0.0.0 --port 8000
      --metrics
      --no-webui
      --offline
    networks:
      - back_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['${VLLM_GPU_DEVICE}']
            capabilities: [gpu]

  vllm_emb:
    image: 'ghcr.io/ggml-org/llama.cpp:server-cuda12-b8840'
    runtime: nvidia
    ipc: host
    volumes:
      - ./llama-models:/models
    command: >
      -m ${LLAMA_EMB_MODEL}
      --jinja
      -fa 1 -ngl 15
      --host 0.0.0.0 --port 8000
      --embedding
      --metrics
      --no-webui
      --offline
    networks:
      - back_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['${VLLM_GPU_DEVICE}']
            capabilities: [gpu]
            
  vllm_rank:
    image: 'ghcr.io/ggml-org/llama.cpp:server-cuda12-b8840'
    runtime: nvidia
    ipc: host
    volumes:
      - ./llama-models:/models
    command: >
      -m ${LLAMA_RANK_MODEL}
      --jinja
      -fa 1 --rerank
      -ub 1024
      --host 0.0.0.0 --port 8000
      --metrics
      --no-webui
      --offline
    networks:
      - back_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['${VLLM_GPU_DEVICE}']
            capabilities: [gpu]

  litellm:
    image: ghcr.io/berriai/litellm:v1.80.11-stable.1
    volumes:
      - ./etc/litellm_config.yaml:/app/config.yaml
    environment:
      - OTEL_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=litellm
      - OTEL_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
    ports:
      - 4000:4000
    networks:
      - back_net
    command: --config /app/config.yaml
    depends_on:
      vllm_llm:
        condition: service_healthy
      vllm_emb:
        condition: service_healthy
      vllm_rank:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v3.9.1
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - observe_net
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:12.3
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./etc/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    networks:
      - observe_net
    depends_on:
      - prometheus
      - loki
      - tempo

  loki:
    image: grafana/loki:main-93650c0
    volumes:
      - ./etc/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observe_net

  tempo:
    image: grafana/tempo:main-63ff9db
    volumes:
      - ./etc/tempo.yaml:/etc/tempo.yaml
    command: -target=all -config.file=/etc/tempo.yaml
    ports:
      - 3200:3200
    networks:
      - observe_net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.149.0
    command: --config=/etc/otel-collector-config.yaml
    volumes:
      - ./etc/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4317:4317
      - 4318:4318
    networks:
      - back_net
      - observe_net

networks:
  back_net:
  observe_net:
  airflow_net: