services:
  qdrant:
    image: qdrant/qdrant:v1.16
    restart: unless-stopped
    volumes:
      - ./qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
      
  vllm_llm:
    image: 'ghcr.io/ggml-org/llama.cpp:server-cuda12-b8132'
    runtime: nvidia
    ipc: host
    volumes:
      - ./llama-models:/models
    command: >
      -m ${LLAMA_LLM_MODEL}
      --jinja
      -fa 1 -ncmoe 30
      -c 32768
      --temp 0.7
      --min-p 0.0 --top-p 0.80 --top-k 20
      --repeat-penalty 1.1
      --host 0.0.0.0 --port 8000
      --metrics
      --no-webui
    networks:
      - back_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['${VLLM_GPU_DEVICE}']
            capabilities: [gpu]

  vllm_emb:
    image: 'ghcr.io/ggml-org/llama.cpp:server-cuda12-b8132'
    runtime: nvidia
    ipc: host
    volumes:
      - ./llama-models:/models
    command: >
      -m ${LLAMA_EMB_MODEL}
      --jinja
      -fa 1 -ngl 15
      --host 0.0.0.0 --port 8000
      --embedding
      --metrics
      --no-webui
    networks:
      - back_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['${VLLM_GPU_DEVICE}']
            capabilities: [gpu]

  litellm:
    image: ghcr.io/berriai/litellm:v1.80.11-stable.1
    volumes:
      - ./etc/litellm_config.yaml:/app/config.yaml
    ports:
      - 4000:4000
    networks:
      - back_net
    command: --config /app/config.yaml
    depends_on:
      vllm_llm:
        condition: service_healthy
      vllm_emb:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v3.9.1
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - back_net
    depends_on:
      vllm_llm:
        condition: service_healthy
      vllm_emb:
        condition: service_healthy

  grafana:
    image: grafana/grafana:12.3
    ports:
      - 3000:3000
    networks:
      - back_net
    depends_on:
      - prometheus

networks:
  back_net:
